name: Build v2ray dat
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# Исправляет первое предупреждение, принудительно включая Node.js 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false # Исправляет второе предупреждение (отключает поиск go.sum)

      - name: Build dat file
        run: |
          git clone --depth=1 https://github.com/v2fly/domain-list-community.git dlc
          
          mkdir -p custom_data
          if [ -f "tv.txt" ]; then
            cp tv.txt custom_data/tv
          elif [ -f "tv" ]; then
            cp tv custom_data/tv
          fi
          
          cd dlc
          go run ./ --datapath=../custom_data
          
          cd ..
          cp dlc/dlc.dat ./myrules.dat

      - name: Deploy to Release Branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          mkdir publish
          cp myrules.dat publish/
          
          git checkout --orphan release
          git rm -rf .
          mv publish/myrules.dat .
          rm -rf publish
          
          git add myrules.dat
          git commit -m "Update myrules.dat"
          git push -f origin release
